#!/bin/bash

###############################################################################
# TaskPilot Blueprint - Project Generation Script
#
# This script orchestrates the complete generation of a Phase 1 task
# management application using the TaskPilot blueprint skill.
#
# Usage:
#   ./generate-project.sh <app-name> [options]
#
# Examples:
#   ./generate-project.sh MyTaskApp
#   ./generate-project.sh MyApp --features "priorities,tags" --database file
#
###############################################################################

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BLUEPRINT_DIR="$( dirname "$SCRIPT_DIR" )"
TEMPLATES_DIR="$BLUEPRINT_DIR/templates"

# Default values
APP_NAME=""
DESCRIPTION="A production-ready task management application"
FEATURES=""
STYLE="light"
DATABASE="memory"
PYTHON_VERSION="3.13+"
INCLUDE_TUI=true
INIT_GIT=true
TARGET_DIR=""

###############################################################################
# Functions
###############################################################################

print_header() {
    echo -e "${BLUE}╔═════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║  TaskPilot Blueprint - Project Generator            ║${NC}"
    echo -e "${BLUE}╚═════════════════════════════════════════════════════╝${NC}"
    echo ""
}

print_step() {
    echo -e "${BLUE}[Step $1]${NC} $2"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
    exit 1
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

# Parse command-line arguments
parse_args() {
    if [ $# -lt 1 ]; then
        print_error "App name is required. Usage: $0 <app-name> [options]"
    fi

    APP_NAME="$1"
    shift

    while [[ $# -gt 0 ]]; do
        case $1 in
            --description)
                DESCRIPTION="$2"
                shift 2
                ;;
            --features)
                FEATURES="$2"
                shift 2
                ;;
            --style)
                STYLE="$2"
                shift 2
                ;;
            --database)
                DATABASE="$2"
                shift 2
                ;;
            --python-version)
                PYTHON_VERSION="$2"
                shift 2
                ;;
            --no-tui)
                INCLUDE_TUI=false
                shift
                ;;
            --no-git)
                INIT_GIT=false
                shift
                ;;
            --target)
                TARGET_DIR="$2"
                shift 2
                ;;
            *)
                print_error "Unknown option: $1"
                ;;
        esac
    done

    # Set target directory
    if [ -z "$TARGET_DIR" ]; then
        TARGET_DIR="$PWD/$APP_NAME"
    fi
}

# Validate inputs
validate_inputs() {
    print_step 1 "Validating inputs"

    # Validate app name
    if ! [[ $APP_NAME =~ ^[A-Za-z][A-Za-z0-9]*$ ]]; then
        print_error "Invalid app name. Must start with letter and contain only alphanumeric characters."
    fi

    # Validate style
    if [[ ! "$STYLE" =~ ^(light|dark|auto)$ ]]; then
        print_error "Invalid style. Must be: light, dark, or auto"
    fi

    # Validate database
    if [[ ! "$DATABASE" =~ ^(memory|file|sql)$ ]]; then
        print_error "Invalid database. Must be: memory, file, or sql"
    fi

    # Check if target directory exists
    if [ -d "$TARGET_DIR" ]; then
        print_warning "Target directory already exists: $TARGET_DIR"
        read -p "Overwrite? (y/n) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            print_error "Cancelled by user"
        fi
        rm -rf "$TARGET_DIR"
    fi

    print_success "Input validation passed"
}

# Create project structure
create_structure() {
    print_step 2 "Creating project structure"

    mkdir -p "$TARGET_DIR"/{src,tests,specs/{features,contracts},.specify/{memory,templates,scripts},.claude/agents,history/prompts/general}

    print_success "Project structure created"
}

# Copy templates
copy_templates() {
    print_step 3 "Copying templates"

    # This would copy all template files
    # For now, we'll just create placeholder messages
    print_info "Templates would be copied from: $TEMPLATES_DIR"
    print_success "Templates staged"
}

# Generate content
generate_content() {
    print_step 4 "Generating content (delegated to subagents)"

    print_info "Specs will be generated by: spec-generator subagent"
    print_info "Code will be generated by: code-generator subagent"
    print_info "Tests will be generated by: test-generator subagent"
    print_info "Docs will be generated by: documentation-generator subagent"

    print_success "Content generation instructions prepared"
}

# Initialize git
init_git() {
    if [ "$INIT_GIT" = true ]; then
        print_step 5 "Initializing Git repository"

        cd "$TARGET_DIR"
        git init
        git add .
        git commit -m "Initial commit: Generated by TaskPilot Blueprint

Generated: $(date)
App: $APP_NAME
Database: $DATABASE
Features: ${FEATURES:-core only}
"

        print_success "Git repository initialized"
        cd - > /dev/null
    fi
}

# Validate output
validate_output() {
    print_step 6 "Validating generated project"

    if [ ! -d "$TARGET_DIR" ]; then
        print_error "Project directory not created"
    fi

    print_success "Project structure validated"
}

# Print summary
print_summary() {
    echo ""
    echo -e "${GREEN}╔═════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║  Generation Complete!                              ║${NC}"
    echo -e "${GREEN}╚═════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Project Details:"
    echo "  📁 Location: $TARGET_DIR"
    echo "  📱 App Name: $APP_NAME"
    echo "  📝 Description: $DESCRIPTION"
    echo "  💾 Database: $DATABASE"
    echo "  🎨 Style: $STYLE"
    echo "  🐍 Python Version: $PYTHON_VERSION"
    echo "  🖥️  Include TUI: $INCLUDE_TUI"
    echo "  📚 Features: ${FEATURES:-(core only)}"
    echo ""
    echo "Next Steps:"
    echo "  1. cd $TARGET_DIR"
    echo "  2. Review the generated specifications in specs/"
    echo "  3. Run tests: /path/to/.local/bin/uv run pytest tests/ -v"
    echo "  4. Try the CLI: /path/to/.local/bin/uv run python src/main.py --help"
    if [ "$INCLUDE_TUI" = true ]; then
        echo "  5. Launch TUI: /path/to/.local/bin/uv run python -m src.tui"
    fi
    echo ""
    echo "Documentation:"
    echo "  📖 Read QUICK_START.md for 30-second setup"
    echo "  📋 See TUI_GUIDE.md for interactive menu guide"
    echo "  🧪 Check TESTING_GUIDE.md for testing instructions"
    echo ""
}

###############################################################################
# Main Execution
###############################################################################

main() {
    print_header

    parse_args "$@"
    validate_inputs
    create_structure
    copy_templates
    generate_content

    if [ "$INIT_GIT" = true ]; then
        init_git
    fi

    validate_output
    print_summary
}

# Run main function
main "$@"
